// Generated by CoffeeScript 1.6.2
(function() {
  $('input[type=text]').change(function() {
    var $this, color;

    $this = $(this);
    if ($this.val() === '') {
      $this.css('background-color', '').removeClass('dark');
      return;
    }
    color = $.color($this.val());
    $this.css('background-color', color.css());
    if (color.lightness() <= 0.5) {
      return $this.addClass('dark');
    } else {
      return $this.removeClass('dark');
    }
  });

  $('#Action').click(function() {
    var average, blue, diffgb, diffrb, diffrg, epsilon, first, green, nonzero, percent, red, result, second;

    epsilon = 0.02;
    first = $.color($('#First').val());
    second = $.color($('#Second').val());
    result = $.color($('#Result').val());
    if (!first || !second || !result) {
      $('#Alpha').addClass('error').text('Enter the colors.');
      return;
    }
    red = (result.red() - first.red()) / (second.red() - first.red());
    green = (result.green() - first.green()) / (second.green() - first.green());
    blue = (result.blue() - first.blue()) / (second.blue() - first.blue());
    if (isNaN(red)) {
      red = 0;
    }
    if (isNaN(green)) {
      green = 0;
    }
    if (isNaN(blue)) {
      blue = 0;
    }
    console.log("RGB:", red, green, blue);
    diffrg = Math.abs(red - green);
    diffrb = Math.abs(red - blue);
    diffgb = Math.abs(green - blue);
    console.log("Deltas:", diffrg, diffrb, diffgb);
    if ((red < 0) || (green < 0) || (blue < 0) || (red > 1) || (green > 1) || (blue > 1) || (diffrg > epsilon) || (diffgb > epsilon) || (diffrb > epsilon)) {
      $('#Alpha').addClass('error').text('Impossible.');
      return;
    }
    nonzero = [red, green, blue].filter(function(c) {
      return c > 0;
    });
    average = (red + green + blue) / nonzero.length;
    if (isNaN(average)) {
      average = 0;
    }
    percent = Math.round(average * 100);
    return $('#Alpha').removeClass('error').text(percent + '%');
  });

}).call(this);
